export const SET_SERVERLESS_URI = 'SET_SERVERLESS_URI';
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';
export const SET_SYNC_CLIENT = 'SET_SYNC_CLIENT';

export const SET_MY_PAGE_STATE = 'SET_MY_PAGE_STATE';
export const ADD_VOICE_WARNING_STATE = 'ADD_VOICE_WARNING_STATE';
export const REMOVE_VOICE_WARNING_STATE = 'REMOVE_VOICE_WARNING_STATE';
