export const SET_EXECUTION_CONTEXT = 'SET_EXECUTION_CONTEXT';
export const SET_SYNC_CLIENT = 'SET_SYNC_CLIENT';
export const SET_LATEST_CALLER = 'SET_LATEST_CALLER';
export const ADD_CALL = 'ADD_CALL';
export const REMOVE_CALL = 'REMOVE_CALL';
export const ADD_VOICE_WARNING_STATE = 'ADD_VOICE_WARNING_STATE';
export const REMOVE_VOICE_WARNING_STATE = 'REMOVE_VOICE_WARNING_STATE';
